// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5-SjLIKRm_itqmeaWJE5z9ThipLTZlMM',
    appId: '1:1061409571599:web:ed0a4ebcb3d7da472ab47a',
    messagingSenderId: '1061409571599',
    projectId: 'mynotes-16242',
    authDomain: 'mynotes-16242.firebaseapp.com',
    storageBucket: 'mynotes-16242.appspot.com',
    measurementId: 'G-32DJVSFSTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFrYvbFaldn2GhmYdSLVPFQLYKOPsp_YM',
    appId: '1:1061409571599:android:754905e3afb0c05f2ab47a',
    messagingSenderId: '1061409571599',
    projectId: 'mynotes-16242',
    storageBucket: 'mynotes-16242.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0jsmL1eTTncmJNKubbmiWKXqfDEkiaQ4',
    appId: '1:1061409571599:ios:22c72a715eabcadd2ab47a',
    messagingSenderId: '1061409571599',
    projectId: 'mynotes-16242',
    storageBucket: 'mynotes-16242.appspot.com',
    iosClientId: '1061409571599-h6oav5ss8tbcjqlflpi200t754h25dp3.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
